### ISSUE TITLE
Help for icon

### ISSUE THREAD

**Issue by SubhamTyagi** [SubhamTyagi/android-ocr#1]
Could any body make the icon for this app?

**Comment by mondlicht-und-sterne** [comment]
hi, I have seen half of your issue and would like to paint the logo in acrylic, this one : https://insmac.org/uploads/posts/2019-10/1572195321_ocrwizard.png

i apply apps from fdroid and opensource projects under [mastodon]([url](https://mastodon.technology/web/accounts/97574/media) with the #hashtag #mastoart with my account 
and also on [pixelfed.social](https://pixelfed.social/mondstern), which delights many people. 
and after the corona time there are also exhibitions planned.

so i would be happy if i can paint this ;)

**Comment by IzzySoft** [comment]
@SubhamTyagi Mondstern is the artist I've told you about.

**Comment by mondlicht-und-sterne** [comment]
![ocr](https://user-images.githubusercontent.com/61406324/77851483-b7941a80-71d9-11ea-8832-a3b3394a4572.jpg)

@SubhamTyagi   
@IzzySoft 

#selfpainted #acrylicpicture #ocr

**Comment by IzzySoft** [comment]
There was already an offer to make the corresponding SVG ("shouldn't be too hard to turn that into a SVG" – I accepted that as an offer :rofl:). I hope the donor (not Mondstern) will add that here soon :smiley:

**Comment by SubhamTyagi** [comment]
i am very grateful

Thank you @mondlicht-und-sterne

**Comment by mondlicht-und-sterne** [comment]
thank you very much, I'm glad. @SubhamTyagi

**Comment by nucleus-ffm** [comment]
Hi, 
I also designed a logo. If you want, you can use it. But if someone has a better one, that wouldn't be so bad either. I can also upload it again as SVG file if needed. 
![Logo](https://user-images.githubusercontent.com/58828815/77853368-27a79e00-71e4-11ea-8504-8f45cd79cf32.png)

**Comment by SubhamTyagi** [comment]
Thank you so much for your appreciative work
@nucleus-ffm  @mondlicht-und-sterne 
@IzzySoft 
and a

**Comment by IzzySoft** [comment]
@SubhamTyagi if you will use this (which is clearly based on the Acryl of @mondlicht-und-sterne :wink:) I can signal the other "technician" he no longer needs to do the SVG. That fine with all of you?

Thanks to @mondlicht-und-sterne & @nucleus-ffm!

**Comment by SubhamTyagi** [comment]
> I can signal the other "technician" he no longer needs to do the SVG. That fine with all of you?

o.k. 👍

**Comment by nucleus-ffm** [comment]
Do you still need the SVG file for the logo? or not?

**Comment by SubhamTyagi** [comment]
> Do you still need the SVG file for the logo? or not?

That would be a great if you provide svg.

**Comment by nucleus-ffm** [comment]
I cannot upload the SVG file here directly, so you can find the file [here](https://github.com/nucleus-ffm/app-logos/tree/master/OCR-app) If you want me to change anything else, let me know.

**Comment by SubhamTyagi** [comment]
@nucleus-ffm Thank you 
i will update app icon soon...., will do it without svg...

**Comment by SubhamTyagi** [comment]
@nucleus-ffm could you provide some link, info. of yourself so i can update them in readme file

**Comment by nucleus-ffm** [comment]
@SubhamTyagi I have a mastodon account: [Nucleus](https://social.tchncs.de/@Nucleus). If you mention my Github account and my Mastodon account, that would be perfect. You don't have to write much about me.

**Comment by IzzySoft** [comment]
@SubhamTyagi could you please attach the APK again to the release, until your app is available at F-Droid? Or shall I just stop my updater from looking for new versions?

**Comment by SubhamTyagi** [comment]
i have uploaded the apks files @IzzySoft

**Comment by IzzySoft** [comment]
Thanks @SubhamTyagi! Should you make a new release before your app gets listed at f-droid.org, please attach the APK there, too :wink:

**Comment by User1l0** [comment]
> Could any body make the icon for this app?

![Logo](https://user-images.githubusercontent.com/77343026/107850035-c5598b00-6dff-11eb-8b15-6271fc952ba1.png)
