### ISSUE TITLE
Add preserve_interword_spaces=1 argument

### ISSUE THREAD

**Issue by languagemaniac** [SubhamTyagi/android-ocr#109]
Hi, when I OCR Japanese text, it comes out with random spaces.

This can be easily fixed by adding "-c preserve_interword_spaces=1" as an argument when executing tesseract.

I tried it on my PC with the same result. Adding that argument fixes the issue.

For what I've been reading, it's the same for Chinese and Korean, (though I haven't tried with those) so maybe there should be an option to enable / disable that specific argument, as these languages don't have any interword spaces whatsoever.

**Comment by T8RIN** [comment]
- I will try to add this in my app

**Comment by languagemaniac** [comment]
> - I will try to add this in my app

Which app?

**Comment by T8RIN** [comment]
ImageToolbox
