### ISSUE TITLE
Translations into other languages with weblate.org

### ISSUE THREAD

**Issue by nautilusx** [SubhamTyagi/android-ocr#13]
Thanks for your great app!

Can you please use weblate.org to further facilitate translations into other languages.
Weblate is really great, easy to use for translation and gratis/free for free software projects.

**Comment by SubhamTyagi** [comment]
I have just applied for libre hosting. You can find the Weblet hosting [here ](https://hosted.weblate.org/projects/android-ocr/). Currently Libre request is pending and now it is in trial mode, I don't now how much time they will take to process request.

Thank you.

**Comment by SubhamTyagi** [comment]
#14 you had updated the wrong file in that MR

**Comment by SubhamTyagi** [comment]
they accepted the libre plan 
Thank you Weblate
