### ISSUE TITLE
updated app icon

### ISSUE THREAD

**Issue by nucleus-ffm** [SubhamTyagi/android-ocr#15]
I have redesigned the app icon. Maybe you want to replace it? What do you think?

![OCR-app-logo](https://user-images.githubusercontent.com/58828815/106359116-d17a1e80-6310-11eb-86d8-a9032de803bd.png)

**Comment by nautilusx** [comment]
Looks very good. I like it!

**Comment by SubhamTyagi** [comment]
@nucleus-ffm Could you also provide the svg file?

**Comment by nucleus-ffm** [comment]
Sure. I cannot attach the SVG file here. You can find it in my  [repo.](https://github.com/nucleus-ffm/app-logos/blob/master/OCR-app/OCR-app-logo-v2-normal.svg) 

Will you use the new logo in the next update?

**Comment by SubhamTyagi** [comment]
done
