### ISSUE TITLE
TrainedData Download Process

### ISSUE THREAD

**Issue by pinalpandav** [SubhamTyagi/android-ocr#29]
How can I pass the path of assets folder instead of downloading the traineddata file.

**Comment by SubhamTyagi** [comment]
What's **assets folder**
Did it mean pre-downloaded trained data files folder?

**Comment by pinalpandav** [comment]
Yes

**Comment by SubhamTyagi** [comment]
copy your pre downloaded files to `/storage/emulated/0/Android/data/io.github.subhamtyagi.ocr/files/best` if you are using best data model

**Comment by SubhamTyagi** [comment]
> How can I pass the path of assets folder instead of downloading the traineddata file.

Due to restrictions from new Android (10 and newer) passing  the data path from arbitrary location is not possible ( although it is possible but not a good option)

**Comment by pinalpandav** [comment]
Okay Thanks.
