### ISSUE TITLE
when app requests downloading the training data selected language  DL FAILS [ bug]

### ISSUE THREAD

**Issue by GintokiHub** [SubhamTyagi/android-ocr#3]
After telling "yes download data" ( tried fast , standard , best) for four different languages .
: app 'downloads' screen asking about if I want to download  resets and reappears within 4 seconds.
Nothing downloads.

**Comment by nucleus-ffm** [comment]
Same problem here. I have tested Android 9 and 10.

**Comment by Grossdm** [comment]
I have the same problem on my OnePlus 6T, Android 10.
This is my first time trying the app - does the previous release still work?

**Comment by voxitme** [comment]
Exact same problem on Oneplus 6 Lineage 17.1

**Comment by voxitme** [comment]
Exact same here on Oneplus 6 - Lineage 17.1
Here is the logcat
[2020-09-23-16-39-09.txt](https://github.com/SubhamTyagi/android-ocr/files/5268926/2020-09-23-16-39-09.txt)

**Comment by voxitme** [comment]
Issue can temporarily get fixed by simply manually
1/ creating the path /storage/emulated/0/tesseract4/standard/tessdata/ and
2/ putting the chosen downloaded files from https://raw.githubusercontent.com/tesseract-ocr/tessdata/4.0.0/ (e.g https://raw.githubusercontent.com/tesseract-ocr/tessdata/4.0.0/eng.traineddata for the English language)
3/ relaunching the app

**Comment by nucleus-ffm** [comment]
@voxitme So you can avoid the download error, but in my case the app always crashes during image recognition. Does that work for you?

**Comment by voxitme** [comment]
> @voxitme So you can avoid the download error, but in my case the app always crashes during image recognition. Does that work for you?

No, same here. See https://github.com/SubhamTyagi/android-ocr/issues/4 ;)

**Comment by SubhamTyagi** [comment]
could you test new version

 https://github.com/SubhamTyagi/android-ocr/releases/download/v1.1/app-arm64-v8a-release.apk

**Comment by nucleus-ffm** [comment]
@SubhamTyagi  The download now works and the app no longer crashes.
