### ISSUE TITLE
Fastlane error

### ISSUE THREAD

**Issue by IzzySoft** [SubhamTyagi/android-ocr#5]
Just a minor thing: I noticed you've "misnamed" `full_description.txt` (you've named it `full_discription.txt`, so it won't be found). A simple `git mv full_discription.txt full_description.txt` should fix that :wink:

**Comment by SubhamTyagi** [comment]
>Just a minor thing: I noticed you've "misnamed" full_description.txt


 These file are manually added by me, that was a human thing.  Thanks for point out this.

I hope this app will be ready(quality wise and more features) for F-Droid inclusion soon.
