### ISSUE TITLE
not downloading data 

### ISSUE THREAD

**Issue by aseelalawy** [SubhamTyagi/android-ocr#6]
when i run the project and the downloading data it will be held for more than 8h or long time then i dont see any result 

2020-12-05 00:50:29.093 28784-28786/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x70 in tid 28786 (Binder:28784_1), pid 28784 (cmd) 
and this error shows when the data was downloading

**Comment by SubhamTyagi** [comment]
>more than 8h or long time

😀 salute to your patience

**Comment by SubhamTyagi** [comment]
could you test new version

https://github.com/SubhamTyagi/android-ocr/releases/download/v1.1/app-arm64-v8a-release.apk

**Comment by SubhamTyagi** [comment]
fixed
