### ISSUE TITLE
BUG: Freezed app after the try to install 3rd language & no possibility to switch languages 

### ISSUE THREAD

**Issue by Moostek** [SubhamTyagi/android-ocr#88]
Hello, i allowed multiple languages setting as i wanted to intsall several languages (about 10). I installed and downloaded learning data for 1st and then for 2nd language. When i tried to install 3rd language (i choosed the third language and i clicked "back"), then the OCR app freezed and since this time I am not able open it. The only solution is to reinstalled it. 

So it seems that only two languages are functional with OCR. I thought that i can download multiple learning language data and then i can switch between them. But this is not obviously possible. Even i have two languages downloaded there is no way to switch from one to each other. Why? The only way to choose desired language is to go to the settings and select new languages... This is too cumbersome! 

Can you fix it, please? I think that it will be great to have downloaded several languages and then to switch in between them. 

Thank you.  

LineageOS 16.0 (Android 9) / OCR 4.0

**Comment by bearyjd** [comment]
I have the same issue, but get the crash with two languages.

**Comment by SD61** [comment]
join the problem. Even the second one doesn't work.
